# Generated by Django 4.2.4 on 2023-08-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='intern',
            name='company_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='intern',
            name='contact_num',
            field=models.CharField(max_length=200, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='intern',
            name='course',
            field=models.CharField(max_length=200, null=True, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='intern',
            name='profile_image',
            field=models.ImageField(default='images/default_profile_image.png', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='intern',
            name='student_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Student ID'),
        ),
    ]
