# Generated by Django 4.2.4 on 2023-08-26 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_intern_address_intern_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_update', models.CharField(max_length=1000)),
                ('recommendation_list', models.CharField(max_length=1000)),
                ('notices', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/documents/')),
            ],
        ),
        migrations.AddField(
            model_name='intern',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='intern',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('excused', 'Excused'), ('absent', 'Absent')], max_length=20, null=True),
        ),
    ]
