# Generated by Django 4.2.4 on 2023-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_intern_internrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='internRelation',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
