# Generated by Django 4.2.4 on 2023-08-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_remove_announcement_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='news_update',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='notices',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='recommendation_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='AnnouncementContent',
        ),
    ]
