# Generated by Django 4.2.4 on 2023-08-28 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_announcement_document_announcement_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_list', models.CharField(max_length=1000, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/documents/')),
            ],
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='news_update',
            new_name='announcement_list',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='notices',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='recommendation_list',
        ),
    ]
