# Generated by Django 4.2.4 on 2023-08-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_recommendation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='document',
            new_name='document_announcement',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='image',
            new_name='image_announcement',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='document',
            new_name='document_recommendation',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='image',
            new_name='image_recommendation',
        ),
    ]
