# Generated by Django 4.2.4 on 2023-09-04 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_timerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='time_out',
        ),
        migrations.AddField(
            model_name='timerecord',
            name='is_time_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
