# Generated by Django 4.2.4 on 2023-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_remove_timerecord_intern_remove_timerecord_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='action',
            field=models.CharField(choices=[('Time In', 'Time In'), ('Time Out', 'Time Out')], default='Time In', max_length=8),
        ),
    ]
