# Generated by Django 4.2.4 on 2023-09-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0013_internshipcalendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternshipCalendar',
        ),
    ]
