# Generated by Django 4.2.4 on 2023-09-16 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0014_delete_internshipcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_month', models.IntegerField()),
                ('starting_date', models.IntegerField()),
                ('ending_month', models.IntegerField()),
                ('ending_date', models.IntegerField()),
                ('weekly_workshift', models.CharField(max_length=100)),
                ('timeshift', models.CharField(max_length=100)),
                ('rest_days', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
