# Generated by Django 4.2.4 on 2023-09-16 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_internshipcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='intern_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
