# Generated by Django 4.2.4 on 2023-09-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0019_dailyaccomplishmentreport_interncalendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaccomplishmentreport',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
