# Generated by Django 4.2.4 on 2023-09-17 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0020_dailyaccomplishmentreport_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaccomplishmentreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
