# Generated by Django 4.2.4 on 2023-09-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0021_alter_dailyaccomplishmentreport_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interncalendar',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyAccomplishmentReport',
        ),
        migrations.DeleteModel(
            name='InternCalendar',
        ),
    ]
