# Generated by Django 4.2.4 on 2023-09-17 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0022_remove_interncalendar_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternsCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAccomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text_submission', models.TextField(blank=True)),
                ('document_submission', models.FileField(blank=True, upload_to='documents/')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internshipcalendar')),
            ],
        ),
    ]
