# Generated by Django 4.2.4 on 2023-09-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0023_internscalendar_dailyaccomplishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaccomplishment',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internscalendar'),
        ),
    ]
