# Generated by Django 4.2.4 on 2023-09-18 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0025_remove_internscalendar_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternsCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAccomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text_submission', models.TextField()),
                ('document_submission', models.FileField(upload_to='documents/')),
                ('interns_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internscalendar')),
            ],
        ),
    ]
