# Generated by Django 4.2.4 on 2023-09-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0026_internscalendar_dailyaccomplishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='internscalendar',
            name='num_submission_bins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
