# Generated by Django 4.2.4 on 2023-09-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0027_internscalendar_num_submission_bins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaccomplishment',
            name='document_submission',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
