# Generated by Django 4.2.4 on 2023-09-24 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0032_alter_dailyaccomplishment_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(choices=[('Acceptance Form for OJT', 'Acceptance Form for OJT'), ('Internship Agreement', 'Internship Agreement'), ('Merit of Rating', 'Merit of Rating')], max_length=100)),
                ('document_image', models.ImageField(upload_to='documents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
