# Generated by Django 4.2.4 on 2023-09-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0034_alter_document_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='middle_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='intern',
            name='suffix',
            field=models.CharField(max_length=200, null=True, verbose_name='suffix'),
        ),
    ]
