# Generated by Django 4.2.4 on 2023-09-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0035_intern_middle_name_intern_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='position',
            field=models.CharField(max_length=200, null=True, verbose_name='Position'),
        ),
    ]
