# Generated by Django 4.2.4 on 2023-09-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0036_intern_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='contact_num',
        ),
    ]
