# Generated by Django 4.2.4 on 2023-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0037_remove_intern_contact_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='internscalendar',
            name='start_week_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
