# Generated by Django 4.2.4 on 2023-09-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0038_internscalendar_start_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaccomplishment',
            name='is_rest_day',
            field=models.BooleanField(default=False),
        ),
    ]
