# Generated by Django 4.2.4 on 2023-10-03 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0052_remove_timerecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='interns_calendar',
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
