# Generated by Django 4.2.4 on 2023-10-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0053_remove_timerecord_interns_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='interns_calendar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.internscalendar'),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='timestamp',
            field=models.DateTimeField(default=True),
        ),
    ]
