# Generated by Django 4.2.4 on 2023-10-03 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0057_timerecord_is_time_out_alter_timerecord_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 15, 12, 28, 574038)),
        ),
    ]
