# Generated by Django 4.2.4 on 2023-10-04 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0058_alter_timerecord_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='is_time_out',
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='is_time_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 8, 40, 17, 124419)),
        ),
    ]
