# Generated by Django 4.2.4 on 2023-10-04 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0059_remove_timerecord_is_time_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 8, 40, 42, 270806)),
        ),
    ]
