# Generated by Django 4.2.4 on 2023-10-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0062_intern_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaccomplishment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
