# Generated by Django 4.2.4 on 2023-10-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0064_timerecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaccomplishment',
            name='hours_submission',
            field=models.TextField(null=True),
        ),
    ]
